-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-keep class com.p2pchat.random.** { *; }
-dontwarn javax.annotation.**
-keep class com.google.mlkit.** { *; }
